### ISSUE TITLE
Add a screenshot and readme

### ISSUE THREAD

**Issue by amarcadet** [mattglover/DSXActivityIndicator#1]
Would be great if could put a screenshot showing your component in action and a readme explaining how to use you it.

**Comment by amarcadet** [comment]
Neat :+1:

**Comment by amarcadet** [comment]
You have a typo in your README:
`DSXActivityIndicator *spinner = [DSXActivityIndicator alloc] init];`
There is a missing `[`.

**Comment by mattglover** [comment]
Nice find, thank you :+1: 
I'm fairly new to public sharing .. but I love to feeling of releasing something that potentially you and others can use/enjoy. 

Always looking to improve, keep the suggestions coming :)

**Comment by mattglover** [comment]
@amarcadet :smile:
